version: '3'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test-admin
      POSTGRES_PASSWORD: test-pass
      POSTGRES_DB: testdb
    volumes:
      - /var/lib/test-db:/var/lib/postgresql/data
